version: '3'
services:
  weather-display:
    container_name: weather-display
    image: ghcr.io/lpgera/weather-display:m5paper-backend
    env_file: .env
    ports:
      - 3000:3000
    restart: unless-stopped
