const font = require('oled-font-5x7')
const icons = require('./icons')
const display = require('./display')

display.clearDisplay()
display.turnOnDisplay()
display.drawRGBAImage(icons.thunder, 0, 0)
display.setCursor(70, 0)
display.writeString(font, 1, 'Temp.:', 1, false)
display.setCursor(70, 11)
display.writeString(font, 2, '-12°C', 0, false)
display.setCursor(70, 35)
display.writeString(font, 1, 'Rain:', 1, false)
display.setCursor(70, 45)
display.writeString(font, 2, '100%', 0, false)
